#ifndef  __IIC_H
#define  __IIC_H

#include <stdint.h>

#define EEPROM_I2C_WR	0		/* 写控制bit */
#define EEPROM_I2C_RD	1		/* 读控制bit */	
#define EEPROM_GPIO_PORT_I2C	GPIOB			/* GPIO端口 */

#define EEPROM_I2C_SCL_Pin		GPIO_PIN_6			/* 连接到SCL时钟线的GPIO */
#define EEPROM_I2C_SDA_Pin		GPIO_PIN_7			/* 连接到SDA数据线的GPIO */

#define EE_WP_Pin GPIO_PIN_8
#define EE_WP_GPIO_Port GPIOB
	
#define EEPROM_I2C_SCL_1()  EEPROM_GPIO_PORT_I2C->BSRR = EEPROM_I2C_SCL_Pin				/* SCL = 1 */
#define EEPROM_I2C_SCL_0()  EEPROM_GPIO_PORT_I2C->BRR = EEPROM_I2C_SCL_Pin				/* SCL = 0 */

                    
#define EEPROM_I2C_SDA_1()  EEPROM_GPIO_PORT_I2C->BSRR = EEPROM_I2C_SDA_Pin				/* SDA = 1 */
#define EEPROM_I2C_SDA_0()  EEPROM_GPIO_PORT_I2C->BRR = EEPROM_I2C_SDA_Pin				/* SDA = 0 */

#define EEPROM_I2C_SDA_READ()  ((EEPROM_GPIO_PORT_I2C->IDR & EEPROM_I2C_SDA_Pin) != 0)	/* 读SDA口线状态 */

void i2c_Start(void);
void i2c_Stop(void);
void i2c_SendByte(uint8_t _ucByte);
uint8_t i2c_ReadByte(void);
uint8_t i2c_WaitAck(void);
void i2c_Ack(void);
void i2c_NAck(void);
uint8_t i2c_CheckDevice(uint8_t _Address);
void i2c_CfgGpio(void);
 void i2c_Delay(void);

#endif
